GRANT CONNECT, RESOURCE TO luudatabase;
GRANT CREATE TABLE, CREATE PROCEDURE TO luudatabase;
GRANT EXECUTE ON DBMS_CRYPTO TO luudatabase;
SELECT name FROM v$services;
ALTER USER luudatabase IDENTIFIED BY uaa;
ALTER USER luudatabase ACCOUNT UNLOCK;

-- Ch?y b?ng quy?n SYS ho?c SYSTEM
ALTER SESSION SET "_ORACLE_SCRIPT" = true; 
GRANT EXECUTE ON DBMS_CRYPTO TO luudatabase;