select * from PDBORCL
GRANT ALTER USER TO luudatabase CONTAINER=ALL;
GRANT CREATE PROFILE TO luudatabase CONTAINER=ALL;
ALTER SESSION SET CONTAINER = PDBORCL;
ALTER USER <ten_user_can_gan> PROFILE <ten_profile>;
SELECT *FROM v$pdbs WHERE name = 'PDBORCL';
SELECT owner, table_name
FROM dba_tables
WHERE tablespace_name = 'QLVT_TS';

SHOW CON_NAME;
SELECT username
FROM dba_users
WHERE username = 'DEMOTEST';

CREATE USER demotest
IDENTIFIED BY 123
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;
SHOW CON_NAME;
SELECT username FROM dba_users WHERE username = 'DEMOTEST';
SELECT
    USERNAME,
    TABLESPACE_NAME,
    BYTES / 1024 / 1024 AS USED_MB,
    MAX_BYTES / 1024 / 1024 AS MAX_MB
FROM DBA_TS_QUOTAS
WHERE USERNAME = 'DEMOTEST';
ALTER SESSION SET CONTAINER = ORCL;
SHOW CON_NAME;
SELECT name, open_mode FROM dba_pdbs;
SHOW PDBS;
ALTER SESSION SET CONTAINER = PDBORCL;

GRANT SELECT, INSERT, UPDATE, DELETE
ON LUUDATABASE.VATTU
TO SYS;

