CREATE OR REPLACE PACKAGE ADMIN_USER_MGR AS
    PROCEDURE LIST_USERS(p_cursor OUT SYS_REFCURSOR);

    PROCEDURE CREATE_USER(p_username VARCHAR2, p_password VARCHAR2);

    PROCEDURE CHANGE_PASSWORD(p_username VARCHAR2, p_newpass VARCHAR2);

    PROCEDURE DROP_USER(p_username VARCHAR2);
END ADMIN_USER_MGR;
/
CREATE TABLE USER_APP (
    USERNAME VARCHAR2(50) PRIMARY KEY,
    PASSWORD_HASH VARCHAR2(200),
    IS_LOCKED NUMBER(1) DEFAULT 0
);
