CREATE OR REPLACE PACKAGE RSA AS
    FUNCTION encrypt(p_plainText VARCHAR2, p_publicKey VARCHAR2) RETURN VARCHAR2;
    FUNCTION decrypt(p_encryptText VARCHAR2, p_privateKey VARCHAR2) RETURN VARCHAR2;
END RSA;
/

CREATE OR REPLACE PACKAGE BODY RSA AS

    FUNCTION encrypt(p_plainText VARCHAR2, p_publicKey VARCHAR2) RETURN VARCHAR2 IS
        v_raw RAW(2000);
        v_encoded VARCHAR2(4000);
    BEGIN
        -- Mô ph?ng RSA: n?i key vào text + m? hóa Base64 (cho ??p)
        v_raw := UTL_RAW.CAST_TO_RAW(p_publicKey || ':' || p_plainText);
        v_encoded := UTL_ENCODE.BASE64_ENCODE(v_raw);
        RETURN v_encoded;
    END encrypt;

    FUNCTION decrypt(p_encryptText VARCHAR2, p_privateKey VARCHAR2) RETURN VARCHAR2 IS
        v_raw RAW(2000);
        v_decoded VARCHAR2(4000);
        v_text VARCHAR2(4000);
    BEGIN
        -- Gi?i m? Base64
        v_raw := UTL_ENCODE.BASE64_DECODE(UTL_RAW.CAST_TO_RAW(p_encryptText));
        v_decoded := UTL_RAW.CAST_TO_VARCHAR2(v_raw);

        -- C?t b? ph?n key gi? l?p
        v_text := SUBSTR(v_decoded, INSTR(v_decoded, ':') + 1);
        RETURN v_text;
    END decrypt;

END RSA;
/
CREATE OR REPLACE FUNCTION RSA_SIGN_HASH (
    p_hash IN RAW,
    p_private_key IN CLOB
) RETURN CLOB
AS
    v_sig_raw RAW(32767);
BEGIN
    v_sig_raw := DBMS_CRYPTO.ENCRYPT(
        src => p_hash,
        typ => DBMS_CRYPTO.encrypt_rsa
               + DBMS_CRYPTO.chain_rsa_pkcs1,
        key => p_private_key
    );

    RETURN UTL_RAW.cast_to_varchar2(
        UTL_ENCODE.base64_encode(v_sig_raw)
    );
END;
/
CREATE OR REPLACE FUNCTION HASH_SHA256 (
    p_data IN BLOB
) RETURN RAW
AS
BEGIN
    RETURN DBMS_CRYPTO.HASH(
        p_data,
        DBMS_CRYPTO.HASH_SH256
    );
END;
/
-- B?ng lýu tr? file và ch? k?
CREATE TABLE FILE_SIGN (
    ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    DOC_TYPE VARCHAR2(20),      -- Lo?i tài li?u (Ví d?: HOADON)
    DOC_ID VARCHAR2(50),        -- M? hóa ðõn
    FILENAME VARCHAR2(255),     -- Tên file g?c
    CONTENT_TYPE VARCHAR2(50),  -- application/pdf
    FILE_DATA BLOB,             -- N?i dung PDF ð? k?
    FILE_HASH RAW(32),          -- B?n bãm SHA-256 c?a file ð? ki?m tra s?a ð?i
    SIGNATURE_P7S CLOB,         -- Chu?i ch? k? Base64 t? C#
    SIGNER_CERT BLOB,           -- Ch?ng ch? ngý?i k? (n?u có)
    SIGNED_BY VARCHAR2(50),     -- Tên ngý?i th?c hi?n
    SIGNED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
drop table file_sign_log
-- B?ng nh?t k? ki?m tra tính toàn v?n
CREATE TABLE FILE_SIGN_LOG (
    LOG_ID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FILE_SIGN_ID NUMBER,
    ACTION VARCHAR2(50),        -- VERIFIED
    ACTION_BY VARCHAR2(50),     -- Ngý?i ki?m tra
    ACTION_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DETAIL VARCHAR2(200)        -- K?t qu? ki?m tra
);
-- Hàm bãm d? li?u BLOB (PDF)
CREATE OR REPLACE FUNCTION FUN_HASH_BLOB (p_blob IN BLOB) 
RETURN RAW AS
BEGIN
    RETURN DBMS_CRYPTO.HASH(p_blob, DBMS_CRYPTO.HASH_SH256); -- S? d?ng SHA-256
END;
/

-- Hàm bãm vãn b?n CLOB
CREATE OR REPLACE FUNCTION HASH_SHA256_TEXT (p_text IN CLOB) 
RETURN RAW AS
BEGIN
    RETURN DBMS_CRYPTO.HASH(p_text, DBMS_CRYPTO.HASH_SH256);
END;
/

-- Hàm ki?m tra ch? k? RSA (Mô ph?ng bãm ð?i chi?u)
CREATE OR REPLACE FUNCTION RSA_VERIFY (
    p_data IN CLOB,
    p_signature_hash IN RAW
) RETURN NUMBER AS
BEGIN
    IF HASH_SHA256_TEXT(p_data) = p_signature_hash THEN
        RETURN 1; -- H?p l?
    ELSE
        RETURN 0; -- Không h?p l?
    END IF;
END;
/
-- Th? t?c lýu file ð? k? vào DB
CREATE OR REPLACE PROCEDURE SAVE_SIGNED_PDF_SECURE (
    p_doc_id IN VARCHAR2,
    p_filename IN VARCHAR2,
    p_pdf_signed IN BLOB,
    p_signature IN CLOB,
    p_signed_by IN VARCHAR2
) AS
    v_hash RAW(32);
BEGIN
    -- Tính toán Hash t?i t?ng DB ð? b?o v? d? li?u
    v_hash := FUN_HASH_BLOB(p_pdf_signed);

    INSERT INTO FILE_SIGN (
        DOC_TYPE, DOC_ID, FILENAME, CONTENT_TYPE, 
        FILE_DATA, FILE_HASH, SIGNATURE_P7S, SIGNED_BY
    )
    VALUES (
        'HOADON', p_doc_id, p_filename, 'application/pdf', 
        p_pdf_signed, v_hash, p_signature, p_signed_by
    );

    COMMIT;
END;
/

-- Hàm ki?m tra file có b? s?a ð?i trong DB hay không
CREATE OR REPLACE FUNCTION VERIFY_FILE_INTEGRITY (p_id IN NUMBER) 
RETURN VARCHAR2 AS
    v_blob BLOB;
    v_hash_db RAW(32);
    v_hash_now RAW(32);
BEGIN
    SELECT FILE_DATA, FILE_HASH INTO v_blob, v_hash_db 
    FROM FILE_SIGN WHERE ID = p_id;

    v_hash_now := FUN_HASH_BLOB(v_blob);

    IF v_hash_now = v_hash_db THEN
        RETURN 'FILE TOAN VEN - KHONG BI SUA DOI';
    ELSE
        RETURN 'FILE DA BI THAY DOI TRONG DATABASE';
    END IF;
END;
/